require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/dummy/db/schema.rb'
    - 'spec/support/shared_*/**/*.rb'
    - 'azeroth.gemspec'

RSpec/NestedGroups:
  Max: 5

RSpec/AlignLeftLetBrace:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

RSpec/ExampleLength:
  Exclude:
    - 'spec/integration/readme/**/*_spec.rb'
    - 'spec/integration/yard/**/*_spec.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/integration/readme/**/*_spec.rb'
    - 'spec/integration/yard/**/*_spec.rb'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - 'spec/**/*_spec.rb'

Lint/EmptyClass:
  Enabled: false
