version: 2
workflows:
  version: 2
  test:
    jobs:
      - test
      - build-and-release:
          requires: [test]
          filters:
            branches:
              only:
                - master
jobs:
  test:
    docker:
      - image: darthjee/circleci_stalchild-base:0.0.1
        environment:
          STALCHILD_MYSQL_HOST: mysql
          STALCHILD_MYSQL_PORT: 3306
          STALCHILD_MYSQL_USER: stalchild
          STALCHILD_MYSQL_NAME: stalchild
          STALCHILD_MYSQL_PASSWORD: stalchild
          STALCHILD_PASSWORD_SALT: abcd
      - image: circleci/mysql:5.7
        name: mysql
        environment:
          MYSQL_DATABASE: stalchild_test
          MYSQL_USER: stalchild
          MYSQL_PASSWORD: stalchild
    steps:
      - checkout
      - run:
          name: Set folder
          command: cp source/* source/.??* ./ -r; rm source -rf
      - run:
          name: Prepare Coverage Test Report
          command: cc-test-reporter before-build
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Bower Install
          command: bundle exec rake bower:install
      - run:
          name: Rubocop
          command: rubocop
      - run:
          name: Wait for database
          command: scripts/wait_for_db.sh
      - run:
          name: Migrate
          command: RAILS_ENV=test bundle exec rake db:schema:load
      - run:
          name: RSpec
          command: bundle exec rspec
      - run:
          name: Coverage Test Report
          command: cc-test-reporter after-build --exit-code $?
  build-and-release:
    machine: true
    steps:
      - checkout
      - run:
          name: Make Build
          command: make PROJECT=production_stalchild build
      - run:
          name: Build heroku image
          command: make build-heroku
      - run:
          name: Install Heroku
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: set heroku app
          command: heroku git:remote -a plague-inc
      - run:
          name: Heroku docker login
          command: heroku container:login
      - run:
          name: Release
          command: make release
